# H2 Setting
spring:
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:~/test;AUTO_SERVER=TRUE"
    username: sa
    password: ""

  h2:
    console:
      enabled: "true"
      path: /console