# H2 Setting
spring:
  datasource:
    platform: h2
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver


  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop